### ISSUE TITLE
Enable signing of web3js transactions outside of Nomo App (with NEXT_PUBLIC_FALLBACK_MNEMONIC environment variable)

### ISSUE THREAD

**Issue by nomo-app** [nomo-app/nomo-webon-kit#38]
For ethers.js, this already works with creating a .env.local file and putting in the following content:

_NEXT_PUBLIC_FALLBACK_MNEMONIC=reject .. other 11 words_

**Comment by dev2-nomo** [comment]
rescheduled to a later release
